language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

branches:
  only:
    - V4

before_script:
  - mkdir -p build/logs
  - composer clear-cache
  - composer config --global github-protocols https
  - composer install --no-interaction --prefer-dist --dev
  - composer require satooshi/php-coveralls:* --dev
  - vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

script:
  - vendor/bin/phpcs src/ --standard=PSR2
  - vendor/bin/phpunit
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'php vendor/bin/coveralls -v'

